openapi: 3.1.0
info:
  title: 'ARH DB API Docs'
  description: |
    
    ⚠️ - Returns large payloads.
  version: 'Up to date'

servers:
  - url: https://db.swdrenewedhope.com

paths:
  /api/public/card/{code}:
    get:
      tags: [Cards]
      summary: Return a single card's properties via its code.
      parameters:
        - name: code
          in: path
          required: true
          description: |
            | Part | Details|
            |------|--------|
            | Set ID | Which set the card belongs to (e.g. `01` = Awakenings) |
            | Card ID | Card position within the set, starting at `001`. |

            Therefore, `01001` becomes Captain Phasma, *Awakenings #1*.
          schema:
            type: integer
            example: "01001"
      responses:
        '200':
          description: Returns the properties of a card.
        '404':
          description: This card does not exist.

  /api/public/cards:
    get:
      tags: [Cards]
      summary: ⚠️ Return a list of all cards across all sets. ⚠️
      responses:
        '200':
          description: Returns all cards.
  
  /api/public/cards/{set_code}:
    get:
      tags: [Cards]
      summary: Return all cards belonging to a set.
      parameters:
        - name: set_code
          in: path
          required: true
          description: |
            Takes the codename of a set, for example:


             Awakenings  -> `AW` 


             Way of The Force  -> `WoTF` 
          schema:
            type: string
            example: "AW"
      responses:
        '200':
          description: Returns all cards from set_code. 
        '404':
          description: This set does not exist.  

  /api/public/sets:
    get:
      tags: [Sets]
      summary: Return a list of sets.
      responses:
        '200':
          description: Returns all sets.

  /api/public/formats:
      get:
        tags: [Formats]
        summary: Return a list of formats.
        responses:
          '200':
            description: Returns all formats.

  /api/public/decklist/{decklist_id}:
      get:
        tags: [Decklist]
        summary: Return contents of a decklist.
        parameters:
        - name: decklist_id
          in: path
          required: true
          schema:
            type: string
            example: "2465"
        responses:
          '200':
            description: Returns the decklist.
          '404':
            description: Decklist does not exist.

  /api/public/find:
    get:
      tags:
        - Find
      summary: Return cards matching search critera.
      parameters:
        - name: q
          in: query
          required: false
          description: | 
            Takes several additional parameters, in no particular order and all optional:
            

            For certain parameters, such as subtype, see [here](https://github.com/swdrenewedhope/Star-Wars-Destiny-A-Renewed-Hope-db/blob/main/dbJSON/README.md) for all valid types.


            - Sending something without anything like the below, is taken as cardname.
            

            - `l:` = Subtitle. Quoted.


            - `x:` = Text on card(s). Quoted.


            - `v:` = Flavour text on card(s). Quoted.


            - `f:` = Faction, by exclude. e.g `f:blue|yellow` would only return blue and yellow.
            

            - `s:` = Set. e.g `s:AW`.


            - `m:` = Format. e.g `m:STD`.


            - `t:` = Card type. e.g `t:downgrade`.


            - `b:` = Subtype. e.g `b:ability`.


            - `u:` = Unique. e.g `u:1` (bool).


            - `y:` = Rarity. e.g `y:C`.


            - `a:` = Affiliation. e.g `a:neutral`.


            - `o:`= Cost. e.g `o:1` OR `o>1`.


            - `h:` = Health. e.g `h:1` OR `h>1`.


            - `i:` = Illustrator. e.g `i:"Aldo Katayangi"`
          schema:
            type: string
            example: "Captain Phasma l:\"Elite Trooper\""
      responses:
        '200':
          description: Returns found cards.
        '204':
          description: No cards found matching search term.

  /api/public/decklists/by_date/{date}:
    get:
      tags:
        - Decklist
      summary: Return cards matching date range.
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            example: "2026-09-08"
      responses:
          '200':
            description: Returns decklists within date.
          '404':
            description: No decklists found within date.
    
  /api/public/deck/{id}:
    get:
      tags:
        - Deck
      summary: Return unpublished deck.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "48571"
      responses:
          '200':
            description: Returns deck.
          '404':
            description: Deck does not exist.
          '403':
            description: Deck owner has 'share unpublished decks' disabled.