api_formats:
  path: /formats
  methods: [GET]
  defaults: { _controller: AppBundle:Api:listFormats }

api_sets:
  path: /sets
  methods: [GET]
  defaults: { _controller: AppBundle:Api:listSets }

api_card:
  path: /card/{card_code}
  methods: [GET]
  defaults: { _controller: AppBundle:Api:getCard }

api_cards:
  path: /cards
  methods: [GET]
  defaults: { _controller: AppBundle:Api:listAllCards }

api_cards_set:
  path: /cards/{set_code}
  methods: [GET]
  defaults: { _controller: AppBundle:Api:listCardsBySet }

api_cards_find:
  path: /find
  methods: [GET]
  defaults: { _controller: AppBundle:Api:findCards }

api_decklist:
  path: /decklist/{decklist_id}
  methods: [GET]
  defaults: { _controller: AppBundle:Api:getDecklist }
  requirements: { decklist_id: \d+ }

api_decklists_by_date:
  path: /decklists/by_date/{date}
  methods: [GET]
  defaults: { _controller: AppBundle:Api:listDecklistsByDate }
  requirements: { date: \d\d\d\d-\d\d-\d\d }

user_info:
  path: /user/info
  defaults: {_controller: AppBundle:User:info }

api_public_deck:
  path: /deck/{deck_id}
  methods: [GET]
  defaults: { _controller: AppBundle:Api:getDeck }
  requirements: { deck_id: \d+ }