AppBundle_api_public:
    resource: "@AppBundle/Resources/config/routing/api/routing_api_public.yml"
    prefix:   /public

AppBundle_api_oauth2:
    resource: "@AppBundle/Resources/config/routing/api/routing_api_oauth2.yml"
    prefix:   /oauth2

api_intro:
    path: /
    defaults:
        _controller: AppBundle:Default:apiIntro
    